vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        article:
            uri_prefix: /images/articles/
            upload_destination: '%kernel.project_dir%/assets/images/articles'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
